### ISSUE TITLE
0日目のwhisperが読み込まれない

### ISSUE THREAD

**Issue by yoshinobc** [aiwolf/AIWolfPy#2]
自分の役職がWEREWOLF,かつ0日目において，Update関数が読み込まれた時に0日目のWhisperChatの内容が反映されなく，diff_dateが空になってしまっています．
このバグは自分のエージェントがWEREWOLFの時に発生します．
このバグの再現は以下のリポジトリをcloneしていただき，
https://github.com/yoshinobc/aiwolf

1. `bash Outostarter.sh`
2. `python3 DQN.py -h localhost -p 10000`

をしていただくことで確認をすることができると思います．(update関数が呼ばれたときに"update"diff_data,diff_dataが空の場合は"return",whisper関数が呼ばれたときに"whisper"を出力するようになっています)

**Comment by k-harada** [comment]
ご報告ありがとうございます、version0.5.xを作るタイミングで確認します。
（確かこれserver側の仕様だったような気が・・・）

**Comment by k-harada** [comment]
@yoshinobc 
解決しました。tcp-ip通信の部分で、0日目だけ別口でデータが来るようになっていたのに私が気づかず消してました。
developブランチでは修正されています。（そのうちmasterにマージします）
